stages:
  - build

Ubuntu-subproject-master:
  stage: build
  script:
  - export APPIMAGE_ICON="Neuronize/icons/neuronize.png"
  - export APPIMAGE_REPO="gitlabci@gmrv.es:apps.private"
  - export BUILD_GENERATOR="Ninja"
  - module load OpenMesh-6.3 libQGLViewer-2.6.3
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - bash .gitlab-ci.sh
  tags:
  - ubuntu
  only:
  - master

Ubuntu-subproject:
  stage: build
  script:
  - export BUILD_GENERATOR="Ninja"
  - module load OpenMesh-6.3 libQGLViewer-2.6.3
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - bash .gitlab-ci.sh
  tags:
  - ubuntu
  except:
  - master

OSX-subproject-master:
  stage: build
  script:
  - export DMGAPP_REPO="gitlabci@gmrv.es:apps.private"
  - export BUILD_GENERATOR="Ninja"
  - module load OpenMesh-6.3 Qt-5.9.1 libQGLViewer-2.6.3 soil
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DCMAKE_FRAMEWORK_PATH=$QGLVIEWER_ROOT/usr/local/lib -DSOIL_ROOT_DIR=$SOIL_ROOT_DIR"
  - bash .gitlab-ci.sh
  tags:
  - osx-sierra
  only:
  - master

OSX-subproject:
  stage: build
  script:
  - export BUILD_GENERATOR="Ninja"
  - module load OpenMesh-6.3 Qt-5.9.1 libQGLViewer-2.6.3 soil
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON -DCMAKE_FRAMEWORK_PATH=$QGLVIEWER_ROOT/usr/local/lib -DSOIL_ROOT_DIR=$SOIL_ROOT_DIR"
  - bash .gitlab-ci.sh
  tags:
  - osx-sierra
  except:
  - master

Win7-VS14-x64-subproject:
  stage: build
  script:
  - set WINAPP_REPO=gitlabci@gmrv.es:apps.private
  - call %ENVFILESDIR%\Qt-5.12-vs14.bat
  - call %ENVFILESDIR%\eigen-3.1.2-vs12-x64.bat
  - call %ENVFILESDIR%\OpenMesh-6.3-vs14-x64.bat
  - call %ENVFILESDIR%\QGLViewer-2.6.3-vs14-x64.bat
  - call %ENVFILESDIR%\Boost-1.71-vs14-x64.bat
  - call %ENVFILESDIR%\soil-vs14-x64.bat
  - call %ENVFILESDIR%\glm.bat
  - call %ENVFILESDIR%\glew-1.11.0.bat
  - call %ENVFILESDIR%\glut.bat
  - set PATH=%PATH%;"c:\Program Files\Git\bin"
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set GLEW_ROOT=c:\libs\glew-1.11.0
  - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON -DGLEW_INCLUDE_DIR=%GLEW_INCLUDE_DIR% -DOPENGL_LIBRARY_DIR=c:\libs\freeglut\lib\x64 -DGLUT_INCLUDE_DIR=%GLUT_INCLUDE_DIR% -DGLM_ROOT_DIR=%GLM_ROOT_DIR%
  - bash --login .gitlab-ci.sh
  tags:
  - win7
  except:
  - tags
